[2025-03-24T22:19:10.287+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:19:10.357+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-24T22:19:10.375+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-24T22:19:10.376+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:19:10.744+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-10 00:00:00+00:00
[2025-03-24T22:19:10.775+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4867) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:19:10.778+0000] {standard_task_runner.py:72} INFO - Started process 4882 to run task
[2025-03-24T22:19:10.785+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpoyy_63xl']
[2025-03-24T22:19:10.795+0000] {standard_task_runner.py:105} INFO - Job 120: Subtask php_app1
[2025-03-24T22:19:11.053+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:19:11.537+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andreeppinghaus' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2025-03-24T22:19:11.538+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:19:11.600+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:19:11.602+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T22:19:11.667+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:19:11.717+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:19:11.720+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:19:11.725+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:19:11.771+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:11.804+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20250324T221910, end_date=20250324T221911
[2025-03-24T22:19:11.927+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:19:11.930+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 120 for task php_app1 (Bash command failed. The command returned a non-zero exit code 1.; 4882)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:11.971+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:19:12.029+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:19:12.042+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:24:20.410+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:24:20.568+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-24T22:24:20.712+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-24T22:24:20.727+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:24:20.992+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-10 00:00:00+00:00
[2025-03-24T22:24:21.096+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5294) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:24:21.098+0000] {standard_task_runner.py:72} INFO - Started process 5333 to run task
[2025-03-24T22:24:21.137+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpyaocopm6']
[2025-03-24T22:24:21.142+0000] {standard_task_runner.py:105} INFO - Job 161: Subtask php_app1
[2025-03-24T22:24:21.401+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:24:22.621+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2025-03-24T22:24:22.642+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:24:22.757+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:24:22.760+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T22:24:22.867+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:24:22.888+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:24:22.890+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:24:22.895+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:24:23.014+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:23.064+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20250324T222420, end_date=20250324T222423
[2025-03-24T22:24:23.196+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:24:23.197+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 161 for task php_app1 (Bash command failed. The command returned a non-zero exit code 1.; 5333)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:23.271+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:24:23.442+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:24:23.519+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:27:27.852+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:27:28.025+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-24T22:27:28.067+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-24T22:27:28.068+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:27:28.117+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-10 00:00:00+00:00
[2025-03-24T22:27:28.154+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5746) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:27:28.156+0000] {standard_task_runner.py:72} INFO - Started process 5756 to run task
[2025-03-24T22:27:28.156+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpds7lcwmg']
[2025-03-24T22:27:28.173+0000] {standard_task_runner.py:105} INFO - Job 193: Subtask php_app1
[2025-03-24T22:27:28.400+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:27:29.457+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2025-03-24T22:27:29.461+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:27:29.584+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:27:29.586+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T22:27:29.625+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:27:29.763+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T22:27:29.764+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T22:27:29.767+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T22:27:29.826+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:29.870+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20250324T222728, end_date=20250324T222729
[2025-03-24T22:27:30.275+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:27:30.279+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 193 for task php_app1 (Bash command failed. The command returned a non-zero exit code 125.; 5756)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:30.442+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:27:30.594+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T23:57:29.714+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T23:57:29.746+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-24T23:57:29.763+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-24T23:57:29.764+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T23:57:29.793+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-10 00:00:00+00:00
[2025-03-24T23:57:29.808+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp0czk3p3h']
[2025-03-24T23:57:29.813+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask php_app1
[2025-03-24T23:57:29.815+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=434) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T23:57:29.816+0000] {standard_task_runner.py:72} INFO - Started process 436 to run task
[2025-03-24T23:57:29.982+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [running]> on host 8e89fdaa3360
[2025-03-24T23:57:30.320+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2025-03-24T23:57:30.325+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T23:57:30.386+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T23:57:30.388+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T23:57:30.443+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T23:57:30.539+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T23:57:30.539+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T23:57:30.544+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T23:57:30.605+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:30.662+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20250324T235729, end_date=20250324T235730
[2025-03-24T23:57:30.896+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T23:57:30.897+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task php_app1 (Bash command failed. The command returned a non-zero exit code 125.; 436)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:30.953+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T23:57:30.987+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:18:37.104+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:18:37.155+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-25T00:18:37.199+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-25T00:18:37.200+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:18:37.654+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-10 00:00:00+00:00
[2025-03-25T00:18:37.707+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=433) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:18:37.709+0000] {standard_task_runner.py:72} INFO - Started process 442 to run task
[2025-03-25T00:18:37.735+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp1ytc0fqw']
[2025-03-25T00:18:37.789+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask php_app1
[2025-03-25T00:18:38.493+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [running]> on host 0f77abd8a5ce
[2025-03-25T00:18:41.239+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2025-03-25T00:18:41.251+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:18:41.505+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:18:41.523+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:41.539+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20250325T001837, end_date=20250325T001841
[2025-03-25T00:18:42.240+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:18:42.241+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task php_app1 (Failed to establish connection to any given Docker hosts.; 442)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:42.371+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:18:42.708+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T00:18:42.718+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:25:46.286+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:25:46.327+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-25T00:25:46.346+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-25T00:25:46.347+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:25:46.404+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-10 00:00:00+00:00
[2025-03-25T00:25:46.470+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=248) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:25:46.472+0000] {standard_task_runner.py:72} INFO - Started process 264 to run task
[2025-03-25T00:25:46.487+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp5hmmh716']
[2025-03-25T00:25:46.501+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask php_app1
[2025-03-25T00:25:46.788+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [running]> on host 7e2e363232cf
[2025-03-25T00:25:47.131+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2025-03-25T00:25:47.138+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:25:47.237+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:25:47.280+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:47.324+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20250325T002546, end_date=20250325T002547
[2025-03-25T00:25:47.559+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:25:47.560+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task php_app1 (Failed to establish connection to any given Docker hosts.; 264)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:47.599+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:25:47.763+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T00:25:47.779+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T12:45:35.302+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T12:45:35.376+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-25T12:45:35.412+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-25T12:45:35.413+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T12:45:35.512+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-10 00:00:00+00:00
[2025-03-25T12:45:35.536+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpmxmwej6m']
[2025-03-25T12:45:35.540+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask php_app1
[2025-03-25T12:45:35.549+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=270) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T12:45:35.550+0000] {standard_task_runner.py:72} INFO - Started process 278 to run task
[2025-03-25T12:45:35.758+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [running]> on host c83c0958fca4
[2025-03-25T12:45:35.987+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2025-03-25T12:45:35.991+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T12:45:36.035+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T12:45:36.051+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:36.067+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20250325T124535, end_date=20250325T124536
[2025-03-25T12:45:36.131+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T12:45:36.132+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task php_app1 (Failed to establish connection to any given Docker hosts.; 278)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:36.158+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T12:45:36.194+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T12:45:36.198+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T11:52:50.240+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T11:52:50.588+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-26T11:52:50.656+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-26T11:52:50.671+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T11:52:50.804+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-10 00:00:00+00:00
[2025-03-26T11:52:50.886+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=255) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T11:52:50.887+0000] {standard_task_runner.py:72} INFO - Started process 270 to run task
[2025-03-26T11:52:50.862+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpx_k3bevp']
[2025-03-26T11:52:50.897+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask php_app1
[2025-03-26T11:52:51.189+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [running]> on host c0a4d7e9da1a
[2025-03-26T11:52:51.481+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2025-03-26T11:52:51.483+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T11:52:51.575+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-26T11:52:51.599+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:51.631+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20250326T115250, end_date=20250326T115251
[2025-03-26T11:52:51.706+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T11:52:51.707+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task php_app1 (Failed to establish connection to any given Docker hosts.; 270)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:51.742+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T11:52:51.778+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T11:52:51.785+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T13:38:27.835+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T13:38:27.883+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-26T13:38:27.898+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2025-03-26T13:38:27.899+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T13:38:27.989+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-10 00:00:00+00:00
[2025-03-26T13:38:28.016+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=299) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:38:28.020+0000] {standard_task_runner.py:72} INFO - Started process 315 to run task
[2025-03-26T13:38:28.023+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp987xvp4b']
[2025-03-26T13:38:28.027+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask php_app1
[2025-03-26T13:38:28.377+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-10T00:00:00+00:00 [running]> on host 3d581a580455
[2025-03-26T13:38:29.398+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2025-03-26T13:38:29.403+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T13:38:29.600+0000] {docker.py:345} INFO - Starting docker container from image php-app1
[2025-03-26T13:38:29.606+0000] {docker.py:353} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-03-26T13:38:33.169+0000] {docker.py:69} INFO - array(23) {
[2025-03-26T13:38:33.170+0000] {docker.py:69} INFO -   [0]=>
[2025-03-26T13:38:33.173+0000] {docker.py:69} INFO -   object(stdClass)#2 (3) {
[2025-03-26T13:38:33.174+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.175+0000] {docker.py:69} INFO -     int(0)
[2025-03-26T13:38:33.176+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.177+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:33.177+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.178+0000] {docker.py:69} INFO -     int(1742852307)
[2025-03-26T13:38:33.178+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.179+0000] {docker.py:69} INFO -   [1]=>
[2025-03-26T13:38:33.179+0000] {docker.py:69} INFO -   object(stdClass)#3 (3) {
[2025-03-26T13:38:33.180+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.180+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.181+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.181+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:33.182+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.182+0000] {docker.py:69} INFO -     int(1742852309)
[2025-03-26T13:38:33.183+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.184+0000] {docker.py:69} INFO -   [2]=>
[2025-03-26T13:38:33.184+0000] {docker.py:69} INFO -   object(stdClass)#4 (3) {
[2025-03-26T13:38:33.185+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.185+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.186+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.186+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:33.187+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.188+0000] {docker.py:69} INFO -     int(1742852311)
[2025-03-26T13:38:33.188+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.189+0000] {docker.py:69} INFO -   [3]=>
[2025-03-26T13:38:33.189+0000] {docker.py:69} INFO -   object(stdClass)#5 (3) {
[2025-03-26T13:38:33.190+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.190+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.191+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.191+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:33.191+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.192+0000] {docker.py:69} INFO -     int(1742852314)
[2025-03-26T13:38:33.192+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.193+0000] {docker.py:69} INFO -   [4]=>
[2025-03-26T13:38:33.193+0000] {docker.py:69} INFO -   object(stdClass)#6 (3) {
[2025-03-26T13:38:33.194+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.195+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.195+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.196+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:33.196+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.197+0000] {docker.py:69} INFO -     int(1742996301)
[2025-03-26T13:38:33.198+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.198+0000] {docker.py:69} INFO -   [5]=>
[2025-03-26T13:38:33.199+0000] {docker.py:69} INFO -   object(stdClass)#7 (3) {
[2025-03-26T13:38:33.200+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.202+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.203+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.203+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:33.204+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.206+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:33.207+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.208+0000] {docker.py:69} INFO -   [6]=>
[2025-03-26T13:38:33.209+0000] {docker.py:69} INFO -   object(stdClass)#8 (3) {
[2025-03-26T13:38:33.210+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.213+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.215+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.216+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:33.217+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.217+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:33.218+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.220+0000] {docker.py:69} INFO -   [7]=>
[2025-03-26T13:38:33.221+0000] {docker.py:69} INFO -   object(stdClass)#9 (3) {
[2025-03-26T13:38:33.221+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.222+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.222+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.231+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:33.232+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.233+0000] {docker.py:69} INFO -     int(1742996303)
[2025-03-26T13:38:33.233+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.234+0000] {docker.py:69} INFO -   [8]=>
[2025-03-26T13:38:33.234+0000] {docker.py:69} INFO -   object(stdClass)#10 (3) {
[2025-03-26T13:38:33.235+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.235+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.236+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.236+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:33.236+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.237+0000] {docker.py:69} INFO -     int(1742996304)
[2025-03-26T13:38:33.237+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.237+0000] {docker.py:69} INFO -   [9]=>
[2025-03-26T13:38:33.238+0000] {docker.py:69} INFO -   object(stdClass)#11 (3) {
[2025-03-26T13:38:33.238+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.238+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.239+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.239+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:33.240+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.240+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:33.241+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.242+0000] {docker.py:69} INFO -   [10]=>
[2025-03-26T13:38:33.242+0000] {docker.py:69} INFO -   object(stdClass)#12 (3) {
[2025-03-26T13:38:33.243+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.244+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.244+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.245+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:33.247+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.247+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:33.248+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.249+0000] {docker.py:69} INFO -   [11]=>
[2025-03-26T13:38:33.249+0000] {docker.py:69} INFO -   object(stdClass)#13 (3) {
[2025-03-26T13:38:33.250+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.250+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.251+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.252+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:33.253+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.254+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:33.254+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.255+0000] {docker.py:69} INFO -   [12]=>
[2025-03-26T13:38:33.255+0000] {docker.py:69} INFO -   object(stdClass)#14 (3) {
[2025-03-26T13:38:33.256+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.257+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.257+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.258+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:33.258+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.259+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:33.260+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.260+0000] {docker.py:69} INFO -   [13]=>
[2025-03-26T13:38:33.261+0000] {docker.py:69} INFO -   object(stdClass)#15 (3) {
[2025-03-26T13:38:33.261+0000] {docker.py:69} INFO -     ["
[2025-03-26T13:38:33.262+0000] {docker.py:69} INFO - contador"
[2025-03-26T13:38:33.263+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.264+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.265+0000] {docker.py:69} INFO -     ["container"
[2025-03-26T13:38:33.265+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.266+0000] {docker.py:69} INFO -     string(8) "php-app1
[2025-03-26T13:38:33.266+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.267+0000] {docker.py:69} INFO -     ["
[2025-03-26T13:38:33.267+0000] {docker.py:69} INFO - timestamp
[2025-03-26T13:38:33.268+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.269+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.270+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:33.271+0000] {docker.py:69} INFO - }
[2025-03-26T13:38:33.271+0000] {docker.py:69} INFO -   [14]=>
[2025-03-26T13:38:33.272+0000] {docker.py:69} INFO - object(stdClass)#16 (3) {
[2025-03-26T13:38:33.272+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:33.273+0000] {docker.py:69} INFO - "contador
[2025-03-26T13:38:33.274+0000] {docker.py:69} INFO - "]=>
[2025-03-26T13:38:33.274+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.275+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:33.276+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.277+0000] {docker.py:69} INFO - container
[2025-03-26T13:38:33.279+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.280+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.283+0000] {docker.py:69} INFO -     string(8) "
[2025-03-26T13:38:33.284+0000] {docker.py:69} INFO - php-app2
[2025-03-26T13:38:33.287+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.288+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:33.290+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.291+0000] {docker.py:69} INFO - timestamp
[2025-03-26T13:38:33.294+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.295+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.295+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:33.297+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.298+0000] {docker.py:69} INFO -   [15]=>
[2025-03-26T13:38:33.298+0000] {docker.py:69} INFO -   object(stdClass)#17 (3) {
[2025-03-26T13:38:33.299+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.299+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.301+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.302+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:33.302+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.303+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:33.303+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.305+0000] {docker.py:69} INFO -   [16]=>
[2025-03-26T13:38:33.306+0000] {docker.py:69} INFO -   object(stdClass)#18 (3) {
[2025-03-26T13:38:33.306+0000] {docker.py:69} INFO -     ["contador"
[2025-03-26T13:38:33.309+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.310+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.311+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:33.314+0000] {docker.py:69} INFO - "container"
[2025-03-26T13:38:33.315+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.315+0000] {docker.py:69} INFO - 
[2025-03-26T13:38:33.316+0000] {docker.py:69} INFO - string(8) "
[2025-03-26T13:38:33.316+0000] {docker.py:69} INFO - php-app1
[2025-03-26T13:38:33.317+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.317+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.318+0000] {docker.py:69} INFO - int(1742996310)
[2025-03-26T13:38:33.318+0000] {docker.py:69} INFO - }
[2025-03-26T13:38:33.319+0000] {docker.py:69} INFO -   [17]=>
[2025-03-26T13:38:33.319+0000] {docker.py:69} INFO -   object(stdClass)#19 (3) {
[2025-03-26T13:38:33.320+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:33.320+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.321+0000] {docker.py:69} INFO - contador
[2025-03-26T13:38:33.322+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.335+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.340+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.353+0000] {docker.py:69} INFO -     ["
[2025-03-26T13:38:33.370+0000] {docker.py:69} INFO - container"]=>
[2025-03-26T13:38:33.371+0000] {docker.py:69} INFO - 
[2025-03-26T13:38:33.372+0000] {docker.py:69} INFO - string(8) "
[2025-03-26T13:38:33.373+0000] {docker.py:69} INFO - php-app2
[2025-03-26T13:38:33.373+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.374+0000] {docker.py:69} INFO -     ["timestamp"
[2025-03-26T13:38:33.375+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.375+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:33.377+0000] {docker.py:69} INFO - 
[2025-03-26T13:38:33.377+0000] {docker.py:69} INFO - }
[2025-03-26T13:38:33.378+0000] {docker.py:69} INFO -   [18]=>
[2025-03-26T13:38:33.378+0000] {docker.py:69} INFO - 
[2025-03-26T13:38:33.379+0000] {docker.py:69} INFO - object(stdClass)#20 (3) {
[2025-03-26T13:38:33.380+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.380+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.380+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.381+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:33.381+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.381+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:33.382+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.382+0000] {docker.py:69} INFO -   [19]=>
[2025-03-26T13:38:33.383+0000] {docker.py:69} INFO -   object(stdClass)#21 (3) {
[2025-03-26T13:38:33.383+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.384+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.384+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.384+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:33.385+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.385+0000] {docker.py:69} INFO -     int(1742996311)
[2025-03-26T13:38:33.386+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.386+0000] {docker.py:69} INFO -   [20]=>
[2025-03-26T13:38:33.386+0000] {docker.py:69} INFO -   object(stdClass)#22 (3) {
[2025-03-26T13:38:33.387+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.387+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.387+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:33.388+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.388+0000] {docker.py:69} INFO - container
[2025-03-26T13:38:33.389+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.389+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.390+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:33.390+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:33.391+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.393+0000] {docker.py:69} INFO - timestamp
[2025-03-26T13:38:33.394+0000] {docker.py:69} INFO - "]=>
[2025-03-26T13:38:33.394+0000] {docker.py:69} INFO -     int(1742996311)
[2025-03-26T13:38:33.395+0000] {docker.py:69} INFO - }
[2025-03-26T13:38:33.396+0000] {docker.py:69} INFO -   [21]=>
[2025-03-26T13:38:33.397+0000] {docker.py:69} INFO -   object(stdClass)#23 (3) {
[2025-03-26T13:38:33.398+0000] {docker.py:69} INFO -     ["contador
[2025-03-26T13:38:33.398+0000] {docker.py:69} INFO - "]=>
[2025-03-26T13:38:33.400+0000] {docker.py:69} INFO - int(1)
[2025-03-26T13:38:33.401+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:33.401+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.402+0000] {docker.py:69} INFO - container
[2025-03-26T13:38:33.403+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.403+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.404+0000] {docker.py:69} INFO - 
[2025-03-26T13:38:33.404+0000] {docker.py:69} INFO - string(8) "php-app2
[2025-03-26T13:38:33.405+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.405+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:33.406+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:33.407+0000] {docker.py:69} INFO - timestamp"
[2025-03-26T13:38:33.407+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:33.408+0000] {docker.py:69} INFO - 
[2025-03-26T13:38:33.408+0000] {docker.py:69} INFO - int(1742996312)
[2025-03-26T13:38:33.409+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.410+0000] {docker.py:69} INFO -   [22]=>
[2025-03-26T13:38:33.410+0000] {docker.py:69} INFO -   array(3) {
[2025-03-26T13:38:33.411+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:33.411+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:33.412+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:33.414+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:33.415+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:33.417+0000] {docker.py:69} INFO -     int(1742996313)
[2025-03-26T13:38:33.417+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:33.417+0000] {docker.py:69} INFO - }
[2025-03-26T13:38:34.138+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T13:38:34.139+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20250326T133827, end_date=20250326T133834
[2025-03-26T13:38:34.234+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T13:38:34.263+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:38:34.273+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
